# Generated by Django 5.0.6 on 2024-10-10 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Azkar_categories",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category Name",
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Category Icon",
                        upload_to="azkar/category_icons/",
                        verbose_name="Category Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Zikr",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "zikr_content",
                    models.CharField(
                        help_text="zikr Content",
                        max_length=100,
                        unique=True,
                        verbose_name="zikr Content",
                    ),
                ),
                (
                    "zikr_repetitions",
                    models.IntegerField(
                        help_text="Zikr repetitions",
                        unique=True,
                        verbose_name="Zikr repetitions",
                    ),
                ),
                (
                    "zikr_category",
                    models.ForeignKey(
                        help_text="Zikr Category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Azkar_set",
                        to="Azkar.azkar_categories",
                        verbose_name="Zikr Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "zikr",
                "verbose_name_plural": "Azkar",
            },
        ),
    ]
