# Generated by Django 5.0.6 on 2024-10-10 20:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Azkar", "0003_zikr_binifit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zikr",
            name="zikr_content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
