version: '3.8'

networks:
  backend:
    driver: bridge

volumes:
  django_db_data: {}  
  media_data: {}
  static_vol: {}

services:

  django:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: Islamic_app
    command: >
      uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.py' --reload-include '*.html'
    restart: always
    volumes:
      - ..:/code
      - media_data:/code/Docker/volumes/media # Ensure media directory persists in the directory
      - django_db_data:/code/Docker/volumes/db_volume
      - static_vol:/code/staticfiles
    env_file: 
      - ../ENV/.env.local
    environment:
      - DJANGO_ENV=local
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    container_name: Islamic_redis
    image: redis:latest
    networks:
      - backend

  celery:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: Islamic_celery
    command: celery -A config.settings.celery worker -l info
    volumes:
      - ..:/code
      - ./code/db:/code/Docker/volumes/celery_db  # Ensure SQLite database file persists in the directory
    env_file: 
      - ../ENV/.env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.django  # Specify the settings module
      - DJANGO_ENV=local
    depends_on:
      - redis
    networks:
      - backend

  celery-beat:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: Islamic_celery_beat
    command: celery -A config.settings.celery beat -l info
    volumes:
      - ..:/code
      - ./code/db:/code/Docker/volumes/celery_db  # Ensure SQLite database file persists in the directory
    env_file:
      - ../ENV/.env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.django  # Specify the settings module
      - DJANGO_ENV=local
    depends_on:
      - redis
    networks:
      - backend
