version: '3.8'

services:
  django:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: Islamic_app
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/code
      - ./code/db:/code/db  # Ensure SQLite database file persists in the directory
      - ./media:/code/media  # Ensure media directory persists in the directory
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.base  # Specify the settings module
    depends_on:
      - redis

  celery:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: Islamic_celery
    command: celery -A config worker -l info
    volumes:
      - ..:/code
      - ./code/db:/code/db  # Ensure SQLite database file persists in the directory
    env_file: 
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.base  # Specify the settings module
    depends_on:
      - redis

  celery-beat:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: Islamic_celery_beat
    command: celery -A config beat -l info
    volumes:
      - ..:/code
      - ./code/db:/code/db  # Ensure SQLite database file persists in the directory
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.base  # Specify the settings module
    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: Islamic_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
