# Generated by Django 5.0.6 on 2024-10-11 09:16

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="supplication",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supplication_content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                (
                    "benefit",
                    models.TextField(
                        blank=True,
                        help_text="benefit",
                        null=True,
                        verbose_name="benefit",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplications",
                "verbose_name_plural": "supplications",
            },
        ),
    ]
