name: "CI Pipeline"

# This CI workflow triggers on new PR or push on main branch.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    # Testing project
    name: "Test"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and bring up services
        run: |
          docker compose -f docker-compose.dev.yaml up -d --build
      - name: Print Docker logs for django_gunicorn
        run: |
          docker compose -f docker-compose.dev.yaml logs django_gunicorn

      # Unit Test
      - name: Run tests with pytest
        run: |
          docker compose -f docker-compose.dev.yaml exec django_gunicorn pytest

      # Lint Test
      - name: Run Linting
        run: |
          docker compose -f docker-compose.dev.yaml exec django_gunicorn flake8 .

  # GitHub Security Scanning using CodeQL.This checks security vulnerabilities
  security_scan:
    name: "Security Scanning"
    runs-on: ubuntu-latest
    permissions:
      actions: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Building images and pushing to Dockerhub
  # build_and_push:
  #   name: "Build and Push to Dockerhub"
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs:
  #     - test
  #     - security_scan
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build services
  #       run: |
  #         docker compose -f docker-compose.prod.yaml build
  #     - name: Tag images
  #       run: |
  #         docker tag portfolio-django_gunicorn:latest ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-django_gunicorn:latest
  #         docker tag portfolio-nginx:latest ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-nginx:latest
  #         docker tag portfolio-certbot:latest ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-certbot:latest
  #     - name: push images
  #       run: |
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-django_gunicorn:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-nginx:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-certbot:latest
